In [8]:
import numpy as np 
import pandas as pd

In [9]:
df = pd.read_csv("IEA Global EV Data 2024 new.csv")
df.head(10)

,region,category,parameter,mode,powertrain,year,unit,value,percentage
0,Austria,Historical,EV stock,Cars,BEV,2010,Vehicles,350,"35000,00%"
1,Austria,Historical,EV stock share,Cars,EV,2010,percent,789.999.961.853,"78999996185300,00%"
2,Belgium,Historical,EV stock,Buses,BEV,2010,Vehicles,3,"300,00%"
3,Belgium,Historical,EV sales,Vans,BEV,2010,Vehicles,7,"700,00%"
4,Belgium,Historical,EV stock,Vans,BEV,2010,Vehicles,62,"6200,00%"
5,Belgium,Historical,EV sales,Cars,BEV,2010,Vehicles,48,"4800,00%"
6,Belgium,Historical,EV stock,Cars,BEV,2010,Vehicles,61,"6100,00%"
7,Belgium,Historical,EV sales,Cars,PHEV,2010,Vehicles,8,"800,00%"
8,Belgium,Historical,EV sales share,Cars,EV,2010,percent,9.999.999.776.483,"999999977648300,00%"
9,Belgium,Historical,EV stock,Cars,FCEV,2010,Vehicles,1,"100,00%"

In [10]:
df.info

<bound method DataFrame.info of         region          category           parameter    mode  \
0      Austria        Historical            EV stock    Cars
1      Austria        Historical      EV stock share    Cars
2      Belgium        Historical            EV stock   Buses
3      Belgium        Historical            EV sales    Vans
4      Belgium        Historical            EV stock    Vans
...        ...               ...                 ...     ...
12649    World  Projection-STEPS      EV sales share    Cars
12650    World  Projection-STEPS      EV stock share    Cars
12651    World    Projection-APS  EV charging points      EV
12652    World    Projection-APS  EV charging points      EV
12653    World  Projection-STEPS      EV stock share  Trucks

                    powertrain  year             unit            value  \
0                          BEV  2010         Vehicles              350
1                           EV  2010          percent  789.999.961.853
2                          BEV  2010         Vehicles                3
3                          BEV  2010         Vehicles                7
4                          BEV  2010         Vehicles               62
...                        ...   ...              ...              ...
12649                       EV  2035          percent               55
12650                       EV  2035          percent               31
12651  Publicly available fast  2035  charging points          9400000
12652  Publicly available slow  2035  charging points         15000000
12653                       EV  2035          percent                9

               percentage
0               35000,00%
1      78999996185300,00%
2                 300,00%
3                 700,00%
4                6200,00%
...                   ...
12649            5500,00%
12650            3100,00%
12651       940000000,00%
12652      1500000000,00%
12653             900,00%

[12654 rows x 9 columns]>

In [11]:
df['value'] = pd.to_numeric(df['value'], errors='coerce') 
df['percentage'] = pd.to_numeric(df['percentage'], errors='coerce')

In [14]:
year_count = df['year'].count()
year_mean = df ['year'].mean()
year_median = df['year'].median()
year_mode = df ['year'].mode()[0]
year_range = df['year'].max() -df['year'].min()

print(f"Count: {year_count}, Mean:{year_mean}, Median: {year_median}, Mode: {year_mode}, range: {year_range}")

Count: 12654, Mean:2019.8221115852696, Median: 2020.0, Mode: 2023, range: 25

In [15]:
region_frequncy = df['region'].value_counts()
print(region_frequncy)

region
World                   1250
Europe                  1234
China                   1138
Rest of the world        954
USA                      737
India                    702
EU27                     424
Netherlands              358
France                   358
United Kingdom           345
Denmark                  319
Belgium                  310
Germany                  298
Norway                   270
Sweden                   269
Japan                    260
Spain                    245
Switzerland              245
Canada                   240
Italy                    230
Korea                    209
Finland                  200
Poland                   194
Portugal                 189
New Zealand              185
Brazil                   183
Israel                   148
Austria                  116
Iceland                  115
Chile                    103
Australia                 94
Mexico                    87
Greece                    83
South Africa              83
Turkiye                   83
Hungary                   27
Ireland                   27
Latvia                    27
Costa Rica                27
Colombia                  27
Estonia                   25
Bulgaria                  25
Czech Republic            24
Slovenia                  24
Slovakia                  23
Lithuania                 19
Romania                   19
Seychelles                18
United Arab Emirates      18
Croatia                   15
Luxembourg                15
Thailand                  14
Cyprus                    14
Indonesia                  8
Name: count, dtype: int64

In [16]:
catergory_frequency = df['category'].value_counts()
print(catergory_frequency)

category
Historical          9174
Projection-APS      1742
Projection-STEPS    1738
Name: count, dtype: int64

In [17]:
mode_poportion = df ['mode'].value_counts(normalize = True)
print(mode_poportion)

mode
Cars      0.371898
Buses     0.213055
Vans      0.202940
Trucks    0.139561
EV        0.072546
Name: proportion, dtype: float64